version: 1
exported_at: "2026-05-01T17:06:16.211657+00:00"
entries:
  - plc_name: JAKOTUKKI
    ams_net_id: 192.168.0.11.1.1
    ip_address: 192.168.0.11
    ip_port: 851
    variables:
      - device_class: ""
        friendly_name: LJ_Temperature
        name: HEATING.fbSensor16.OUT
        type: LREAL
        unit: C
        writable: false
        async_read: false
    device_profiles: []
    enable_route_config: true
    route_name: HASS
    route_username: Administrator
    sender_ams: 192.168.0.123.1.1
    route_password_secret: ads_multi_route_password_192_168_0_11_1_1
  - plc_name: TALO_CX7000
    ams_net_id: 192.168.0.10.1.1
    ip_address: 192.168.0.10
    ip_port: 851
    variables: []
    device_profiles:
      - brightness:
          max: 100.0
          min: 0.0
          name: LIGHTS.fbMh2Light.nRemoteBrightness
          type: INT
        id: mh2_katto
        name: MH2 katto
        on_off:
          name: LIGHTS.fbMh2Light.bRemoteControl
          type: BOOL
        profile_type: light
      - brightness:
          max: 100.0
          min: 0.0
          name: LIGHTS.fbMh4Light.nRemoteBrightness
          type: INT
        id: mh4_katto
        name: MH4 katto
        on_off:
          name: LIGHTS.fbMh4Light.bRemoteControl
          type: BOOL
        profile_type: light
    enable_route_config: false
    route_name: ""
    route_username: ""
    sender_ams: 192.168.0.123.1.1
